# Login
POST http://localhost:3001/api/sessions
Content-Type: application/json

{
  "username": "AlainRizzi",
  "password": "alain123"
}

###

# Get current session
GET http://localhost:3001/api/sessions/current

###

# Logout
DELETE http://localhost:3001/api/sessions/current

###

# Get full network (Setup phase)
GET http://localhost:3001/api/network

###

# Get all segments (Planning phase)
GET http://localhost:3001/api/segments

###

# Start a new game
POST http://localhost:3001/api/games
Content-Type: application/json

{}

###

# Submit route
POST http://localhost:3001/api/games/7/route
Content-Type: application/json

{
  "segments": [
    { "station1": "Lotto", "station2": "Pagano" },
    { "station1": "Pagano", "station2": "Cadorna FN" },
    { "station1": "Cadorna FN", "station2": "Cordusio" },
    { "station1": "Cordusio", "station2": "Duomo" }
  ]
}

###

# Submit route
POST http://localhost:3001/api/games/3/route
Content-Type: application/json

{
  "segments": [
    { "station1": "Lotto", "station2": "Pagano" },
    { "station1": "Pagano", "station2": "Cadorna FN" },
    { "station1": "Cadorna FN", "station2": "Cordusio" },
    { "station1": "Cordusio", "station2": "Duomo" }
  ]
}

###

# Submit route false (not connected)   
POST http://localhost:3001/api/games/3/route
Content-Type: application/json

{
  "segments": [
    { "station1": "Lotto", "station2": "Pagano" },
    { "station1": "Pagano", "station2": "Cadorna FN" },
    { "station1": "Cordusio", "station2": "Duomo" }
  ]
}

###

# Submit route bidirectional
POST http://localhost:3001/api/games/3/route
Content-Type: application/json

{
  "segments": [
    { "station1": "Lotto", "station2": "Pagano" },
    { "station1": "Cadorna FN", "station2": "Pagano" },
    { "station1": "Cadorna FN", "station2": "Cordusio" },
    { "station1": "Cordusio", "station2": "Duomo" }
  ]
}

###

# Get ranking
GET http://localhost:3001/api/ranking